### ISSUE TITLE
Does WSO2 EMM provide an abstraction layer API for push notifications to simplify app development?

### ISSUE THREAD

**Issue by kaiyuan01** [wso2-attic/product-emm-1.1.0#16]
Hi,

We are very interested in WSO2 EMM and considering migrate HP Anywhere to WSO2. Does WSO2 provide an abstraction layer for push notifications for app developers, in other words, how do I migrate existing apps in production to WSO2 with minimal code change in push notifications from HP Anywhere mobility framework?

In a nutshell, does WSPO2 provide a simple API to simplify implementing push notifications for app developers, pretty much the same way as HP Anywhere can do here:

HP Anywhere:

http://docs.hpanywhere.com/wp-content/uploads/10.12/HP_Anywhere_Online_Help/Default.htm#Best_Practices/Push_Notifications.htm

http://docs.hpanywhere.com/wp-content/uploads/10.12/HP_Anywhere_API_Reference/webframe.html#Simple_Push.html

BTW, where can I find an official forum for _EMM_ (http://wso2.com/forums has none for EMM) discussions monitored by WSO2?

Thank you.
J

**Comment by dilshanwso2** [comment]
You can raise or open discussions in dev@wso2.org. You should be looking at MDM 2.0 (https://github.com/wso2/product-mdm) which is the next version of EMM which is yet to release in May. In MDM 2.0 these will be exposed as APIs. If you have further questions you may raise them in stackoverflow with the tag wso2.

**Comment by kaiyuan01** [comment]
Thanks for the reply. Can you point me to the right code/folder for that API - abstraction layer to simply push notification implementation for app developers for different platforms(iOS, Android, Windows etc..) as seen in HP Anywhere, SAP SAP Kapsel Push plugin, Apache Cordova PushPlugin, etc..?

Also do you have a version that we can test run this product?

J

**Comment by dilshanwso2** [comment]
MDM suite only focuses on push notification strategies which is needed for MDB operations. Like send messages etc. However as app developers this is not the ideal way to integrate such services. Such push notifications only focuses on one single app which is the agent application for that corresponding platform. Hence ideally you might have to extend this behavior and derive your own to support such. Anyway the implementation of this in progress and will be available soon.
