### ISSUE TITLE
WSO2 EMM Compliance Monitoring not updated

### ISSUE THREAD

**Issue by AMSARAJ** [wso2-attic/product-emm-1.1.0#23]
I am Downloaded latest Binary from http://wso2.com/products/enterprise-mobility-manager/ and started the server successfully.

Steps to re-produce:

1) Login as admin

2) Create a New User

3) Register an Android Device.

4) Create a new Policy with Compliance Monitoring Type:Warning.

5) Add a Blacklisted app to the newly created Policy (com.facebook.katana)

6) Assign newly created User to the newly created Policy

Result: No change in Policy Compliance (Pie chart from Dashboard still shows Compliance - 100%); Device Compliance Monitoring, under Reports shows status: Policy Compliance; No change in Device details under Device Management: No policies to display. To achieve the above concept i followed the tutorial in this link http://wso2.com/library/articles/2014/02/introduction-to-wso2-enterprise-mobility-manager/

any suggestions are welcome. thanks

**Comment by j0rgan** [comment]
It is the case-sensitive issue. Android!=android. Somewhere in the code, i fixed it few months ago.

**Comment by AMSARAJ** [comment]
file location......thanks

**Comment by j0rgan** [comment]
I had some issues again, and I had to go through history. If you didn't find it, then you should find it in a repository/deployment/server/jaggeryapps/emm/modules/device.js

Cheers,
M.
